version: "3"

services:
  frontend:
    image: aimamit/djangorestapi-react/frontend
    build: ./frontend
    restart: always
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    ports:
      - 3000:3000
    depends_on:
      - backend
      - db
    networks:
      - frontend_net
      - backend_net

  # nginx:
  #   image: aimamit/djangorestapi-react/nginx
  #   build: ./nginx
  #   restart: always
  #   volumes:
  #     - static_volume:/vol/web/static
  #     - media_volume:/vol/web/media
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - backend
  #     - db
  #   networks:
  #     - backend_net
  #     - frontend_net

  backend:
    image: aimamit/djangorestapi-react/backend
    build: ./backend
    command: ./run.sh
    ports:
      - 8000:8000
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend_net
      - frontend_net

  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_net

networks:
  backend_net:
  frontend_net:

volumes:
  pgdata:
  static_volume:
  media_volume:
