version: "3"

services:
  frontend:
    image: aimamit/djangorestapi_react_frontend
    build: ./frontend
    restart: always
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    ports:
      - 80:80
    depends_on:
      - backend
      - db
    networks:
      - frontend_net
      - backend_net

  backend:
    image: aimamit/djangorestapi_react_backend
    build: ./backend
    command: ./run.sh
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend_net
      - frontend_net

  redis:
    image: redis:6.0.3-alpine
    depends_on:
      - db
    networks:
      - backend_net

  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_net

networks:
  backend_net:
  frontend_net:

volumes:
  pgdata:
  static_volume:
  media_volume:
