export const AUTH_SIGNIN_START = 'AUTH_SIGNIN_START'
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS'
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL'

export const AUTH_AUTO_LOGIN = 'AUTH_AUTO_LOGIN'
export const AUTH_AUTO_LOGIN_FAIL = 'AUTH_AUTO_LOGIN_FAIL'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const FETCH_TOKEN_AFTER_EXP = 'FETCH_TOKEN_AFTER_EXP'


export const RECIPES_FETCH_START = 'RECIPES_FETCH_START'
export const RECIPES_FETCH_SUCCESS = 'RECIPES_FETCH_SUCCESS'
export const RECIPES_FETCH_FAIL = 'RECIPES_FETCH_FAIL'

export const RECIPE_FETCH_START = 'RECIPE_FETCH_START'
export const RECIPE_FETCH_SUCCESS = 'RECIPE_FETCH_SUCCESS'
export const RECIPE_FETCH_FAIL = 'RECIPE_FETCH_FAIL'

export const RECIPE_IMAGE_FETCH_START = 'RECIPE_IMAGE_FETCH_START'
export const RECIPE_IMAGE_FETCH_SUCCESS = 'RECIPE_IMAGE_FETCH_SUCCESS'
export const RECIPE_IMAGE_FETCH_FAIL = 'RECIPE_IMAGE_FETCH_FAIL'

export const RECIPE_DELETE_START = 'RECIPE_DELETE_START'
export const RECIPE_DELETE_SUCCESS = 'RECIPE_DELETE_SUCCESS'
export const RECIPE_DELETE_FAIL = 'RECIPE_DELETE_FAIL'


export const TAG_CREATE_START = 'TAG_CREATE_START'
export const TAG_CREATE_SUCCESS = 'TAG_CREATE_SUCCESS'
export const TAG_CREATE_FAIL = 'TAG_CREATE_FAIL'
export const TAG_CREATE = 'TAG_CREATE'
export const TAG_REMOVE = 'TAG_REMOVE'
export const TAG_ADD = 'TAG_ADD'


export const INGREDIENT_CREATE_START = 'INGREDIENT_CREATE_START'
export const INGREDIENT_CREATE_SUCCESS = 'INGREDIENT_CREATE_SUCCESS'
export const INGREDIENT_CREATE_FAIL = 'INGREDIENT_CREATE_FAIL'
export const INGREDIENT_CREATE = 'INGREDIENT_CREATE'
export const INGREDIENT_REMOVE = 'INGREDIENT_REMOVE'
export const INGREDIENT_ADD = 'INGREDIENT_ADD'



export const SET_TAGS_INGREDIENTS = 'SET_TAGS_INGREDIENTS'

export const RECIPE_CREATE_START = 'RECIPE_CREATE_START'
export const RECIPE_CREATE_SUCCESS = 'RECIPE_CREATE_SUCCESS'
export const RECIPE_CREATE_FAIL = 'RECIPE_CREATE_FAIL'

export const RECIPE_UPLOAD_IMAGE_START = 'RECIPE_UPLOAD_IMAGE_START'
export const RECIPE_UPLOAD_IMAGE_SUCCESS = 'RECIPE_UPLOAD_IMAGE_SUCCESS'
export const RECIPE_UPLOAD_IMAGE_FAIL = 'RECIPE_UPLOAD_IMAGE_FAIL'

export const RECIPE_CREATE_RESET_ERROR = 'RECIPE_CREATE_RESET_ERROR'



export const USER_TAGS_FETCH_START = 'USER_TAGS_FETCH_START'
export const USER_TAGS_FETCH_SUCCESS = 'USER_TAGS_FETCH_SUCCESS'
export const USER_TAGS_FETCH_FAIL = 'USER_TAGS_FETCH_FAIL'

export const USER_INGREDIENTS_FETCH_START = 'USER_INGREDIENTS_FETCH_START'
export const USER_INGREDIENTS_FETCH_SUCCESS = 'USER_INGREDIENTS_FETCH_SUCCESS'
export const USER_INGREDIENTS_FETCH_FAIL = 'USER_INGREDIENTS_FETCH_FAIL'

export const USER_RECIPES_FETCH_START = 'USER_RECIPES_FETCH_START'
export const USER_RECIPES_FETCH_SUCCESS = 'USER_RECIPES_FETCH_SUCCESS'
export const USER_RECIPES_FETCH_FAIL = 'USER_RECIPES_FETCH_FAIL'

export const USER_FAVOURITES_FETCH_START = 'USER_FAVOURITES_FETCH_START'
export const USER_FAVOURITES_FETCH_SUCCESS = 'USER_FAVOURITES_FETCH_SUCCESS'
export const USER_FAVOURITES_FETCH_FAIL = 'USER_FAVOURITES_FETCH_FAIL'

// export const USER_FAVOURITES_CREATE_START = 'USER_FAVOURITES_CREATE_START'
export const USER_FAVOURITES_CREATE_SUCCESS = 'USER_FAVOURITES_CREATE_SUCCESS'
export const USER_FAVOURITES_CREATE_FAIL = 'USER_FAVOURITES_CREATE_FAIL'


export const USER_DETAILS_FETCH_START = 'USER_DETAILS_FETCH_START'
export const USER_DETAILS_FETCH_SUCCESS = 'USER_DETAILS_FETCH_SUCCESS'
export const USER_DETAILS_FETCH_FAIL = 'USER_DETAILS_FETCH_FAIL'

export const USER_DETAILS_CREATE_START = 'USER_DETAILS_CREATE_START'
export const USER_DETAILS_CREATE_SUCCESS = 'USER_DETAILS_CREATE_SUCCESS'
export const USER_DETAILS_CREATE_FAIL = 'USER_DETAILS_CREATE_FAIL'

export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'